blank_issues_enabled: false
contact_links:
  - name: Vincent OS Repo Issue
    url: https://github.com/Vincent-OS/repo/issues
    about: All Issues about Vincent OS Repo and packages
  - name: Vincent OS Installer Issue
    url: https://github.com/Vincent-OS/calamares-settings/issues
    about: All Issues about the Vincent OS Installer
